### ISSUE TITLE
Better support for git submodules

### ISSUE THREAD

**Issue by mira-kovar** [jbenner-radham/node-changelog-md#1]
Hi,
I have project git submodule. And when at this submodule call node_modules/.bin/changelog generated result has bad links, all target main repository insted the one where i hit generate.

**Comment by jbenner-radham** [comment]
Hello,

I'm afraid I'm slightly confused. This project itself doesn't generate anything in the `.bin` directory however it has a [sibling project](https://github.com/jbenner-radham/node-changelog-md-cli) which does but it creates `node_modules/.bin/changelog-md` instead of `node_modules/.bin/changelog` and both the links it creates are hard coded to [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) and [Semantic Versioning](http://semver.org/spec/v2.0.0.html). Could you post an example of the output being generated?
